### PR TITLE
fix Giscus color theme on initial renders

### PR DESCRIPTION
**Pull request by Eliav2**
[related](https://github.com/zenstackhq/zenstack/issues/1094)

## Summary by CodeRabbit

- **New Features**
	- Integrated Giscus commenting system to enhance user interaction on blog posts and documentation pages.
	- Added metadata generation for blog posts to improve SEO and social media sharing.
	- Introduced layout components for blog posts and documentation items, including navigation, content display, and comments.

- **Enhancements**
	- Updated styling for documentation layouts to improve readability on larger screens.

- **Dependencies**
	- Added new packages to support theme enhancements and commenting features.

### CODE REVIEW

**Comment by jiashengguo** [comment]
@Eliav2, I think it is because you are reusing your old branch that has been squashed.  I have manually resolved the conflict, could you double-check to confirm the change is correct? (You can leave alone the commits, they will be squashed anyway)

However, I tried with the preview build, the issue seems still there: 

https://zenstack-new-site-git-fork-eliav2-main-zenstack.vercel.app/

**Comment by Eliav2** [comment]
hey @jiashengguo are you sure?
could you provide me detailed steps to reproduce(or GIF)? based on my check it does not happens any more, not even in the preview build.

**Comment by jiashengguo** [comment]
It's the same steps as before. I recorded a new one using preview build:
Apr-12-2024 17-30-13

**Comment by Eliav2** [comment]
i'm sorry but i can't reproduce this bug anymore.

1. can you delete site cache and try again?
2. can you try to describe step by step the exact actions you are doing?
3. what browser are you using?

on my browser this issue does not appear to exists anymore

**Comment by jiashengguo** [comment]
@Eliav2 After you click the dark mode on any page,  could you immediately hit refresh to see how it looks?

**Comment by Eliav2** [comment]
ohh now i can see it... on it.

**Comment by Eliav2** [comment]
fixed it by removing backgroundColor on Giscus component.

it should not have happen, and it happens only on production builds. this pr can be merged.

this subtle bug sent me to investigate this weird react behavior (in react devtools i can see hooks value that does not correspond to when being rendered in the DOM, and only on production)

**Comment by jiashengguo** [comment]
@Eliav2, Awesome job! Thanks for the patience on this!

**Pull request merged**
