### PR TITLE
feat: add i18n feature, add zh-cn init config.

### PR DESCRIPTION
**Pull request by Rackar**
Try to translate Zenstack into Chinese, the first step.

### CODE REVIEW

**Comment by ymc9** [comment]
Hey @Rackar , thank you for starting this work!

I thought about it and feel that it's still too early for ZenStack to support multi-lingual documentation. Once started, it needs to be a continous effort. We can probably postpone this effort to a later time when we get a larger user base and more requests from users based in different regions of the world. I'll keep the PR open for future use.

I really appreciate the effort though. It's people who take the initiatives make ZenStack a better project. Please feel free to join the discord server so we can chat more. https://discord.gg/Ykhr738dUe

**Comment by Rackar** [comment]
Thanks for the reply. I will keep it in the fork rep. I'd like try Zenstack, reading Chinese docs is for my prnsonal benefits. And thank you again for your great project.



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 24, 2023 05:02 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zenstackhq/zenstack-docs] feat: add i18n feature, add zh-cn initconfig. (PR #201)




 
Hey @Rackar , thank you for starting this work!
 
I thought about it and feel that it's still too early for ZenStack to support multi-lingual documentation. Once started, it needs to be a continous effort. We can probably postpone this effort to a later time when we get a larger user base and more requests from users based in different regions of the world. I'll keep the PR open for future use.
 
I really appreciate the effort though. It's people who take the initiatives make ZenStack a better project. Please feel free to join the discord server so we can chat more. https://discord.gg/Ykhr738dUe

**Comment by ymc9** [comment]
> Thanks for the reply. I will keep it in the fork rep. I'd like try Zenstack, reading Chinese docs is for my prnsonal benefits. And thank you again for your great project.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Oct 24, 2023 05:02 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [zenstackhq/zenstack-docs] feat: add i18n feature, add zh-cn initconfig. (PR #201) Hey @Rackar , thank you for starting this work! I thought about it and feel that it's still too early for ZenStack to support multi-lingual documentation. Once started, it needs to be a continous effort. We can probably postpone this effort to a later time when we get a larger user base and more requests from users based in different regions of the world. I'll keep the PR open for future use. I really appreciate the effort though. It's people who take the initiatives make ZenStack a better project. Please feel free to join the discord server so we can chat more. https://discord.gg/Ykhr738dUe — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

I'm glad you found ZenStack helpful. Yes, we can keep the fork and PR active for future use.

**Comment by ymc9** [comment]
Closing for now since there's no plan for localization in the new future.

**Pull request closed without merging**
